# Generated by Django 5.1.3 on 2024-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
